env:
  sumo_cfg: /projappl/project_2012159/kbocheni_temp/smas-rl-gnn/configs/small_net.sumocfg
  use_gui: false
  R: 6
  K_max: 3
  N_max: 16
  E_max: 64
  G: 0
  vicinity_m: 2000.0
  max_steps: 2400
  min_episode_steps: 100
  decision_dt: 60
  max_wait_delay_s: 240.0
  max_travel_delay_s: 900.0
  max_robot_capacity: 3
  conflict_resolution: random
  sorted_candidates: false
  two_hop: true
  two_hop_directed: true
  two_hop_critic: true
  two_hop_arch: comp_corr
  reward_params:
    reward_type: wait_travel
    w_comp: 2.0
    w_wait: 1.5
    w_travel: 1.0
    w_deadline: 10.0
    wait_cap: 600.0
    travel_cap: 90.0
    deadline_cap: 600.0
features:
  base_dim: 9
  use_xy_pickup: false
  normalize_features: true
  use_node_type: true
  use_ego_robot: true
  use_edge_rt: true
  edge_features:
  - dx
  - dy
  - eta
  - is_ego_edge
  robot_commitment: route_slots
  route_slots_k: 2
seeds:
  train:
  - 100
  - 200
  - 300
  - 400
  - 500
  - 600
  - 700
  - 800
  - 900
  - 1000
  - 1100
  - 1200
  - 1300
  - 1400
  - 1500
  - 1600
  - 1700
  - 1800
  - 1900
  - 2000
  eval:
  - 42
  - 123
  - 456
  - 789
  - 1011
  - 1213
  - 1415
  - 1617
  - 1819
  - 2021
ppo:
  policy_kwargs:
    hidden: 128
    k_max: 3
    logit_temperature: 1.0
    noop_init: -1.0
    freeze_noop_logit: true
    gnn_layers: 2
    lambda_init: 0.5
  n_steps: 256
  batch_size: 64
  learning_rate: 0.0003
  gamma: 0.99
  clip_range: 0.2
  clip_range_vf: null
  vf_coef: 0.35
  ent_coef: 0.003
  gae_lambda: 0.95
  n_epochs: 5
  total_timesteps: 120000
logging:
  run_name: 2hop-1_rnd
  out_dir: /scratch/project_2012159/kbocheni/smas-rl-gnn/runs
  model_save_dir: /scratch/project_2012159/kbocheni/smas-rl-gnn/runs/2hop-1_rnd/!saved_models
  log_conflict_metrics: true
  prune_episode_dir_after_metrics: true
  extended_quality_metrics: false
  extended_quality_plots: false
  extended_quality_include_task_level: false
  extended_quality_include_decision_level: false
continue_training: false
baselines:
  policies:
  - random
  - greedy
  - unique
  num_seeds: 10
sorted: false
sumoport: 8813

